<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PeliculaSeeder extends Seeder
{
    /**
     * Seed the peliculas table with 200 popular movie examples.
     */
    public function run(): void
    {
        $titulos = [
            'The Shawshank Redemption',
            'The Godfather',
            'The Dark Knight',
            'Pulp Fiction',
            'Forrest Gump',
            'Inception',
            'Fight Club',
            'The Matrix',
            'Interstellar',
            'Gladiator',
            'Titanic',
            'Avatar',
            'Avengers: Endgame',
            'Avengers: Infinity War',
            'Jurassic Park',
            'The Lion King',
            'Star Wars: A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'The Lord of the Rings: The Fellowship of the Ring',
            'The Lord of the Rings: The Two Towers',
            'The Lord of the Rings: The Return of the King',
            'Harry Potter and the Sorcerer\'s Stone',
            'Harry Potter and the Prisoner of Azkaban',
            'Harry Potter and the Deathly Hallows Part 2',
            'Spider-Man',
            'Spider-Man 2',
            'Spider-Man: No Way Home',
            'Iron Man',
            'Captain America: Civil War',
            'Black Panther',
            'Doctor Strange',
            'Guardians of the Galaxy',
            'Thor: Ragnarok',
            'Deadpool',
            'Logan',
            'The Batman',
            'Joker',
            'Man of Steel',
            'Wonder Woman',
            'Aquaman',
            'Shrek',
            'Toy Story',
            'Toy Story 3',
            'Finding Nemo',
            'Up',
            'Inside Out',
            'Coco',
            'Frozen',
            'Moana',
            'Zootopia',
            'Encanto',
            'Soul',
            'Ratatouille',
            'WALL-E',
            'Monsters, Inc.',
            'Cars',
            'The Incredibles',
            'Incredibles 2',
            'Minions',
            'Despicable Me',
            'Kung Fu Panda',
            'How to Train Your Dragon',
            'Madagascar',
            'Ice Age',
            'The Super Mario Bros. Movie',
            'Barbie',
            'Oppenheimer',
            'Dune',
            'Dune: Part Two',
            'Top Gun: Maverick',
            'Mission: Impossible - Fallout',
            'Mission: Impossible - Dead Reckoning',
            'John Wick',
            'John Wick: Chapter 4',
            'Mad Max: Fury Road',
            'The Revenant',
            'The Wolf of Wall Street',
            'The Departed',
            'Shutter Island',
            'Se7en',
            'Gone Girl',
            'The Social Network',
            'Whiplash',
            'La La Land',
            'The Grand Budapest Hotel',
            'Parasite',
            'Oldboy',
            'Your Name',
            'Spirited Away',
            'Princess Mononoke',
            'Howl\'s Moving Castle',
            'Akira',
            'The Silence of the Lambs',
            'The Green Mile',
            'Saving Private Ryan',
            'Schindler\'s List',
            'The Pianist',
            'Django Unchained',
            'Inglourious Basterds',
            'Kill Bill: Vol. 1',
            'Kill Bill: Vol. 2',
            'Reservoir Dogs',
            'The Hateful Eight',
            'Once Upon a Time in Hollywood',
            'No Country for Old Men',
            'There Will Be Blood',
            'Blade Runner',
            'Blade Runner 2049',
            'Alien',
            'Aliens',
            'Terminator 2: Judgment Day',
            'The Terminator',
            'Back to the Future',
            'Back to the Future Part II',
            'E.T. the Extra-Terrestrial',
            'Jaws',
            'Indiana Jones and the Raiders of the Lost Ark',
            'Indiana Jones and the Last Crusade',
            'Rocky',
            'Creed',
            'Rambo: First Blood',
            'Die Hard',
            'Lethal Weapon',
            'The Exorcist',
            'Halloween',
            'A Nightmare on Elm Street',
            'Scream',
            'It',
            'The Conjuring',
            'Annabelle',
            'Insidious',
            'A Quiet Place',
            'Get Out',
            'Us',
            'The Sixth Sense',
            'The Prestige',
            'Memento',
            'Tenet',
            'Dunkirk',
            'The Imitation Game',
            'Bohemian Rhapsody',
            'Rocketman',
            'Elvis',
            'A Star Is Born',
            'The Greatest Showman',
            'The Truman Show',
            'Cast Away',
            'Catch Me If You Can',
            'The Curious Case of Benjamin Button',
            'The Aviator',
            'Argo',
            'Good Will Hunting',
            'The Pursuit of Happyness',
            'I Am Legend',
            'Men in Black',
            'Independence Day',
            'Bad Boys',
            'Bad Boys for Life',
            'Pirates of the Caribbean: The Curse of the Black Pearl',
            'Pirates of the Caribbean: Dead Man\'s Chest',
            'The Curse of the Were-Rabbit',
            'Sherlock Holmes',
            'Sherlock Holmes: A Game of Shadows',
            'The Hunger Games',
            'Catching Fire',
            'The Maze Runner',
            'Divergent',
            'Twilight',
            'The Fault in Our Stars',
            'Me Before You',
            'The Notebook',
            'Pride & Prejudice',
            'Notting Hill',
            'Pretty Woman',
            'Home Alone',
            'Elf',
            'The Grinch',
            'Hocus Pocus',
            'Beetlejuice',
            'Ghostbusters',
            'Groundhog Day',
            'The Mask',
            'Ace Ventura: Pet Detective',
            'Bruce Almighty',
            'Yes Man',
            'The Hangover',
            'Superbad',
            'Mean Girls',
            'Clueless',
            'Legally Blonde',
            'The Devil Wears Prada',
            'Mamma Mia!',
            'Chicago',
            'The Sound of Music',
            'Grease',
            'Les Miserables',
            'The Intouchables',
            'Slumdog Millionaire',
            'Life of Pi',
            'The Martian',
            'Gravity',
            'Arrival',
            'Everything Everywhere All at Once',
            'The Menu',
            'Knives Out',
            'Glass Onion',
            'The Irishman',
            'Ford v Ferrari',
            '1917',
            'Jojo Rabbit',
        ];

        $clasificaciones = ['G', 'PG', 'PG-13', 'R'];
        $idiomas = ['Ingles', 'Espanol', 'Frances', 'Coreano', 'Japones'];
        $paises = ['Estados Unidos', 'Reino Unido', 'Canada', 'Francia', 'Corea del Sur', 'Japon'];
        $directores = ['Christopher Nolan', 'Steven Spielberg', 'Martin Scorsese', 'Denis Villeneuve', 'Quentin Tarantino', 'Greta Gerwig', 'Ridley Scott', 'James Cameron', 'Patty Jenkins', 'Bong Joon-ho'];
        $guionistas = ['Jonathan Nolan', 'Aaron Sorkin', 'Phoebe Waller-Bridge', 'Taylor Sheridan', 'Nora Ephron', 'Damien Chazelle', 'Jordan Peele', 'Noah Baumbach', 'Emerald Fennell', 'Sorkin & Team'];
        $productoras = ['Warner Bros.', 'Universal Pictures', 'Paramount Pictures', '20th Century Studios', 'Sony Pictures', 'Marvel Studios', 'Pixar', 'DreamWorks', 'A24', 'Netflix Studios'];
        $plataformas = ['Netflix', 'Prime Video', 'Disney+', 'Max', 'Apple TV+', 'Paramount+'];
        $estados = ['en cartelera', 'proxima', 'archivada'];

        $peliculas = collect($titulos)
            ->take(200)
            ->values()
            ->map(function (string $titulo, int $index) use ($clasificaciones, $idiomas, $paises, $directores, $guionistas, $productoras, $plataformas, $estados) {
                $numero = $index + 1;
                $anio = 1972 + ($index % 53);
                $duracion = 95 + (($index * 7) % 85);
                $popularidad = max(70, 99.5 - ($index * 0.12));
                $calificacion = min(9.8, 7.4 + (($index % 18) * 0.1));
                $votos = 12000 + ($index * 1850);
                $presupuesto = 18000000 + ($index * 2750000);
                $multiplicador = 2.8 + (($index % 9) * 0.37);
                $slug = Str::slug($titulo);

                return [
                    'titulo' => $titulo,
                    'slug' => $slug,
                    'descripcion' => sprintf('Ficha editorial de ejemplo para %s, una produccion destacada dentro de un catalogo de peliculas populares. El registro incluye datos pensados para pruebas de listados, filtros y vistas de detalle.', $titulo),
                    'sinopsis_corta' => sprintf('%s combina entretenimiento, alto reconocimiento del publico y metadatos utiles para escenarios de prueba.', $titulo),
                    'anio_estreno' => $anio,
                    'duracion' => $duracion,
                    'clasificacion_edad' => $clasificaciones[$index % count($clasificaciones)],
                    'idioma_original' => $idiomas[$index % count($idiomas)],
                    'pais_origen' => $paises[$index % count($paises)],
                    'director' => $directores[$index % count($directores)],
                    'guionista' => $guionistas[$index % count($guionistas)],
                    'productora' => $productoras[$index % count($productoras)],
                    'presupuesto' => number_format($presupuesto, 2, '.', ''),
                    'recaudacion' => number_format($presupuesto * $multiplicador, 2, '.', ''),
                    'calificacion_promedio' => number_format($calificacion, 1, '.', ''),
                    'total_votos' => $votos,
                    'popularidad' => number_format($popularidad, 2, '.', ''),
                    'estado' => $estados[$index % count($estados)],
                    'fecha_estreno_streaming' => now()->copy()->subDays($numero * 3)->toDateString(),
                    'plataforma' => $plataformas[$index % count($plataformas)],
                    'trailer_url' => sprintf('https://trailers.example.com/%s', $slug),
                    'poster_url' => sprintf('https://images.example.com/posters/%s.jpg', $slug),
                    'fondo_url' => sprintf('https://images.example.com/backgrounds/%s.jpg', $slug),
                    'fecha_creacion' => now(),
                    'fecha_actualizacion' => now(),
                ];
            })
            ->all();

        DB::table('peliculas')->upsert(
            $peliculas,
            ['slug'],
            [
                'titulo',
                'descripcion',
                'sinopsis_corta',
                'anio_estreno',
                'duracion',
                'clasificacion_edad',
                'idioma_original',
                'pais_origen',
                'director',
                'guionista',
                'productora',
                'presupuesto',
                'recaudacion',
                'calificacion_promedio',
                'total_votos',
                'popularidad',
                'estado',
                'fecha_estreno_streaming',
                'plataforma',
                'trailer_url',
                'poster_url',
                'fondo_url',
                'fecha_actualizacion',
            ]
        );
    }
}